global using Catalog.Models;
global using Microsoft.EntityFrameworkCore;
global using Catalog.Data;
global using MassTransit;
global using ServiceDefaults.Messaging.Events;
global using Catalog.EndPoints;
global using Catalog.Services;
global using ServiceDefaults.Messaging;
global using System.Reflection;